AdminPortal.UI/Controllers/ManageCourseController.cs
using AdminPortal.BL.BusinessClasses;
using AdminPortal.UI.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace AdminPortal.UI.Controllers
{
    /// <summary>
    /// Controller to manage courses
    /// </summary>
   
    [Authorize]
    public class ManageCourseController : Controller
    {
        #region Fields

        /// <summary>
        /// Field to the logger 
        /// </summary>
        private readonly ILogger<ManageCourseController> _logger;

        /// <summary>
        /// Field to the course business object class
        /// </summary>
        private readonly Course courseBusinessObject;

        #endregion

        #region Constructors



        /// <summary>
        /// Constructor that takes in a logger 
        /// </summary>
        /// <param name="logger">the logger to be used</param>
        public ManageCourseController(ILogger<ManageCourseController> logger)
        {
            _logger = logger;
            courseBusinessObject = new Course();
        }

        #endregion


        /// <summary>
        /// Get action to the index page of manage courses
        /// </summary>
        /// <returns>A view to the manage course page</returns>
      
       
        public async Task<IActionResult> Index()
        {
            return View("Views/Course/ManageCourse.cshtml",await courseBusinessObject.GetAllCourseAsync());
        }

        /// <summary>
        /// Get action to add or edit a course 
        /// </summary>
        /// <param name="id">The id of the course for an add or edit</param>
        /// <returns>A view to the manage course page</returns>
        public async Task<IActionResult> AddEditCourse(int id = 0)
        {
            //add new course
            if (id == 0)
                return View("Views/Course/AddEditCourse.cshtml", new CourseModel());
            else
            {
                //edit
                var foundCourse = await courseBusinessObject.FindCourseAsync(id);
                return View("Views/Course/AddEditCourse.cshtml", foundCourse);
            }
        }

        /// <summary>
        /// Post action to perform the add or edit
        /// </summary>
        /// <param name="course">The course to be added or edited</param>
        /// <returns>A view back to the manage course home page</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditCourse([Bind("CourseId,Name,Description")] CourseModel course)
        {
            if (ModelState.IsValid)
            {
                //add to the database
                if (course.CourseId == 0)
                    await courseBusinessObject.AddCourseAsync(course);

                //edit
                else
                    await courseBusinessObject.UpdateCourseAsync(course);

                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index), course);
        }

        /// <summary>
        /// Get action to delete a course 
        /// </summary>
        /// <param name="id">The id of the course to be deleted</param>
        /// <returns>A view back to manage course home page</returns>
        public async Task<IActionResult> DeleteCourse(int id)
        {
            var student = await courseBusinessObject.DeleteCourseAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AdminPortal.UI/Controllers/ManageStudentController.cs
using AdminPortal.UI.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using AdminPortal.BL.BusinessClasses;

namespace AdminPortal.UI.Controllers
{
    /// <summary>
    /// Controller to manage students
    /// </summary>
 
    [Authorize]
    public class ManageStudentController : Controller
    {

        #region Fields

        /// <summary>
        /// Field to the logger
        /// </summary>
        private readonly ILogger<ManageStudentController> _logger;

        /// <summary>
        /// Field to the student business object
        /// </summary>
        private readonly Student studentBusinessObject;

        #endregion

        #region Constructors

        /// <summary>
        /// Constructor that takes in a logger 
        /// </summary>
        /// <param name="logger">The logger to use</param>
        public ManageStudentController(ILogger<ManageStudentController> logger)
        {
            _logger = logger;
            studentBusinessObject = new Student();
        }

        #endregion


        /// <summary>
        /// Get action to the index page of manage students
        /// </summary>
        /// <returns>A view to the manage student page</returns>
        public async Task<IActionResult> Index()
        {
            return View("Views/Student/ManageStudent.cshtml",await studentBusinessObject.GetAllStudentAsync());
        }

        /// <summary>
        /// GET action to add or edit a student 
        /// </summary>
        /// <param name="id">the  id of the student for an add or edit</param>
        /// <returns>A view back to the manage student home page</returns>
        public async Task<IActionResult> AddEditStudent(int id = 0)
        {
            //add new student
            if (id == 0)
                return View("Views/Student/AddEditStudent.cshtml", new StudentModel());
            else
            {
                //edit
                var foundStudent = await studentBusinessObject.FindStudentAsync(id);
                return View("Views/Student/AddEditStudent.cshtml", foundStudent);
            }
        }

        /// <summary>
        /// Post action to add or edit a student
        /// </summary>
        /// <param name="student">The student to be added or edited</param>
        /// <returns>A view back to the mange student home page</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditStudent([Bind("StudentId,FirstName,LastName")] StudentModel student)
        {

            if (ModelState.IsValid)
            {
                //add to the database
                if (student.StudentId == 0)
                    await studentBusinessObject.AddStudentAsync(student);

                //edit
                else
                    await studentBusinessObject.UpdateStudentAsync(student);

                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index), student);
        }

        /// <summary>
        /// Get action to delete a student from the database
        /// </summary>
        /// <param name="id">The id of the student to delete</param>
        /// <returns>A view back to the manage student page</returns>
        public async Task<IActionResult> DeleteStudent(int id)
        {
            var student = await studentBusinessObject.DeleteStudentAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

AdminPortal.UI/Controllers/ManageTeacherController.cs
using AdminPortal.BL.BusinessClasses;
using AdminPortal.UI.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace AdminPortal.UI.Controllers
{
    /// <summary>
    /// Controller to manage teachers
    /// </summary>
    [Authorize]
    public class ManageTeacherController : Controller
    {
        #region Fields

        /// <summary>
        /// Field to the logger 
        /// </summary>
        private readonly ILogger<ManageTeacherController> _logger;

        /// <summary>
        /// Field to the teacher business object class
        /// </summary>
        private readonly Teacher teacherBusinessObject;

        #endregion

        #region Constructors



        /// <summary>
        /// Constructor that takes in a logger 
        /// </summary>
        /// <param name="logger">the logger to be used</param>
        public ManageTeacherController(ILogger<ManageTeacherController> logger)
        {
            _logger = logger;
            teacherBusinessObject = new Teacher();
        }

        #endregion


        /// <summary>
        /// Get action to the index page of manage teachers
        /// </summary>
        /// <returns>A view to the manage teacher page</returns>
        public async Task<IActionResult> Index()
        {
            return View("Views/Teacher/ManageTeacher.cshtml", await teacherBusinessObject.GetAllTeacherAsync());
        }

        /// <summary>
        /// Get action to add or edit a teacher 
        /// </summary>
        /// <param name="id">The id of the teacher for add or edit</param>
        /// <returns>A view to the manage teacher page</returns>
        public async Task<IActionResult> AddEditTeacher(int id = 0)
        {
            //add new teacher
            if (id == 0)
                return View("Views/Teacher/AddEditTeacher.cshtml", new TeacherModel());
            else
            {
                //edit
                var foundTeacher = await teacherBusinessObject.FindTeacherAsync(id);
                return View("Views/Teacher/AddEditTeacher.cshtml", foundTeacher);
            }
        }

        /// <summary>
        /// Post action to perform the add or edit
        /// </summary>
        /// <param name="teacher">The teacher to be added or edited</param>
        /// <returns>A view back to the manage teacher home page</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditTeacher([Bind("TeacherId,FirstName,LastName")] TeacherModel teacher)
        {
            if (ModelState.IsValid)
            {
                //add to the database
                if (teacher.TeacherId == 0)
                    await teacherBusinessObject.AddTeacherAsync(teacher);

                //edit
                else
                    await teacherBusinessObject.UpdateTeacherAsync(teacher);

                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index), teacher);
        }

        /// <summary>
        /// Get action to delete a teacher 
        /// </summary>
        /// <param name="id">The id of the teacher to be deleted</param>
        /// <returns>A view back to manage teacher home page</returns>
        public async Task<IActionResult> DeleteTeacher(int id)
        {
            var student = await teacherBusinessObject.DeleteTeacherAsync(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

AdminPortal.UI/Controllers/StudentEnrollmentController.cs
using AdminPortal.BL.BusinessClasses;
using AdminPortal.UI.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace AdminPortal.UI.Controllers
{
    /// <summary>
    /// Class to manage student enrollment
    /// </summary>
    [Authorize]
    public class StudentEnrollmentController : Controller
    {

        #region Fields

        /// <summary>
        /// Field to the logger
        /// </summary>
        private readonly ILogger<StudentEnrollmentController> _logger;

        /// <summary>
        /// Field to the student business object
        /// </summary>
        private readonly Student studentBusinessObject;

        /// <summary>
        /// Field to the student business object
        /// </summary>
        private readonly Course courseBusinessObject;

        #endregion

        #region Constructors

        /// <summary>
        /// Constructor that takes in a logger 
        /// </summary>
        /// <param name="logger">The logger to use</param>
        public StudentEnrollmentController(ILogger<StudentEnrollmentController> logger)
        {
            _logger = logger;
            studentBusinessObject = new Student();
            courseBusinessObject = new Course();

        }
        #endregion


        #region Actions 

        /// <summary>
        /// Get action method to populate the drop down lists for courses and students
        /// </summary>
        /// <returns>A view to the student enrollment main page</returns>
        public async Task<IActionResult> Index()
        {
            var studentEnrollmentModel = await PopulateStudentAndCourseListAsync();
            return View("Views/Student/StudentEnrollment.cshtml", studentEnrollmentModel);
        }


        /// <summary>
        /// Post action method to enroll a student into a course
        /// </summary>
        /// <param name="student">The student to enroll into the course</param>
        /// <returns>A view to the student enrollment main page</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EnrollStudent([Bind("StudentId,CourseId")] StudentEnrollmentModel student)
        {
            var test = false;

            if (ModelState.IsValid)
                test = await courseBusinessObject.EnrollStudentInCourseAysnc(student.StudentId, student.CourseId);
            
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Non Action Methods

        /// <summary>
        /// No action method to populate the course and student list
        /// </summary>
        /// <returns>A StudentEnrollmentModel</returns>
        [NonAction]
        private async Task<StudentEnrollmentModel> PopulateStudentAndCourseListAsync()
        {
            var studentEnrollmentModel = new StudentEnrollmentModel
            {
                Courses = await courseBusinessObject.GetAllCourseAsync(),
                Students = await studentBusinessObject.GetAllStudentAsync()
            };

            //Add the default value
            studentEnrollmentModel.Students.Insert(0, new StudentModel() { StudentId = 0, FullName = "---Select A Student---" });

            //insert at the first the for selections
            studentEnrollmentModel.Courses.Insert(0, new CourseModel() { CourseId = 0, Name = "---Select A Course---" });

            return studentEnrollmentModel;
        }

        #endregion 
    }
}

AdminPortal.UI/Views/Shared/_Layout.cshtml
@*
This is the Main Layout for users that are not logged into the site
*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AdminPortal.UI/Views/Shared/_LoggedInLayout.cshtml
@* 
This is the Main Layout for the logged in administrator.
Used to navigate to other parts of the site
*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageStudent" asp-action="Index">Manage Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageTeacher" asp-action="Index">Manage Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageCourse" asp-action="Index">Manage Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentEnrollment" asp-action="Index">Enroll Student To Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherEnrollment" asp-action="Index">Assign Teacher To Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>